databases:
  - name: nlmkblablacar-db
    databaseName: nlmkblablacar
    user: nlmkblablacar
    plan: free

services:
  - type: web
    name: nlmkblablacar-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build && npx prisma db push
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nlmkblablacar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
